### ISSUE TITLE
テスト用データベース

### ISSUE THREAD

**Issue by OnoYuta** [OnoYuta/laravel-blog-sample#29]
### Problem

- ローカル環境でテストを実行するたびにDBが初期化される

### Solution

- テスト用データベースを作成する
- テスト実行時はテスト用データベースを使用する

##### テストデータベースを作成するSQLファイルを作成

docker/mysql/init/create-test-db.sql

```sql
CREATE DATABASE IF NOT EXISTS `laravel-blog-sample-test` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

##### 作成したSQLファイルを MySQLコンテナ起動時に読み込む

docker-compose.yml

```
  mysql:
    container_name: ${PROJECT}-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d // 追記
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    tty: true
```

> docker の MySQL image では /docker-entrypoint-initdb.d/ というディレクトリ内に初期化用のSQLやスクリプトを置くことで、最初に image を起動したときにデータの初期化を自動的に行う仕組みがあります。

https://qiita.com/moaikids/items/f7c0db2c98425094ef10

##### テストDB作成を反映させる

```bash
// コンテナとボリュームを削除
docker-compose down --volumes --rmi all
// コンテナの起動
docker-compose up -d --build
```
