### ISSUE TITLE
トップページの外観を実装する

### ISSUE THREAD

**Issue by OnoYuta** [OnoYuta/laravel-blog-sample#66]
### Problem

- 現状はLaravelデフォルトのウェルカムページを使用している

### Solution

- 参考:https://www.shoeisha.com/book/hp/mcoding/3/
- 上記をbootstrapを使用して実装する

### Testing

実装前

![スクリーンショット 2020-05-25 20 06 08](https://user-images.githubusercontent.com/49770211/82807684-38625080-9ec3-11ea-8df7-09a859d460c0.png)

**Comment by OnoYuta** [comment]
## ウェルカムページのスタイルをscssで定義

resources/sass/components/_welcome.scss

```scss
html,
body {
    background-color: #fff;
    color: #636b6f;
    font-family: 'Nunito', sans-serif;
    font-weight: 200;
    height: 100vh;
    margin: 0;
}

.full-height {
    height: 100vh;
}

.flex-center {
    align-items: center;
    display: flex;
    justify-content: center;
}

.position-ref {
    position: relative;
}

.top-right {
    position: absolute;
    right: 10px;
    top: 18px;
}

.content {
    text-align: center;
}

.title {
    font-size: 84px;
}

.links>a {
    color: #636b6f;
    padding: 0 25px;
    font-size: 13px;
    font-weight: 600;
    letter-spacing: .1rem;
    text-decoration: none;
}

.m-b-md {
    margin-bottom: 30px;
}
```

resources/sass/welcome.scss

```scss
// Fonts
@import url('https://fonts.googleapis.com/css?family=Nunito');

// Components
@import 'components/variables';
@import 'components/welcome';

// Bootstrap
@import '~bootstrap/scss/bootstrap';
```

**Comment by OnoYuta** [comment]
## ナビゲーションバーを実装

resources/views/welcome.blade.php

```php
        <!-- nav-bar -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">
                <a href="{{ url('/') }}" class="navbar-brand"><i class="fas fa-braille"></i> {{ config('app.name', 'Laravel') }}</a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#mainNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mainNav">
                    <ul class="navbar-nav ml-auto">
                        @if (Route::has('login'))
                        @auth
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url()->to('home') }}">{{ __('Home') }}</a>
                        </li>
                        @else
                        <li class="nav-item ml-auto">
                            <a class="nav-link" href="{{ url()->to('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item ml-auto">
                            <a class="nav-link" href="{{ url()->to('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @endauth
                        @endif
                        <li class="nav-item">
                    </ul>
                </div>
            </div>
        </nav>
```

_welcome.scss

```scss
// 下記を削除
.top-right {
    position: absolute;
    right: 10px;
    top: 18px;
}
```

![スクリーンショット 2020-05-25 22 11 39](https://user-images.githubusercontent.com/49770211/82815809-df9bb380-9ed4-11ea-9109-a5655378613a.png)
