### ISSUE TITLE
docker-for-macのCPU使用率が高い

### ISSUE THREAD

**Issue by OnoYuta** [OnoYuta/laravel-blog-sample#70]
### Problem

docker-for-macのCPU使用率が高い

### Solution

https://www.deep-rain.com/mac/docker/1423#cacheddelegatedvolume

#### Kubernetesを無効にする

docker->PreferencesでKubernetesが無効になっていることを確認

#### ホストコンテナ間の同期遅延を許可

docker-compose.yml

```
version: "3"
services:
  app:
    container_name: ${PROJECT}-app
    image: utayuta/docker-laravel-alpine:latest
    volumes:
      - "./:/app:cached" // cachedオプションを追加
      - "~/.gitconfig:/etc/gitconfig:cached"
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
```
