### ISSUE TITLE
Laravel-admin外観をカスタマイズ

### ISSUE THREAD

**Issue by OnoYuta** [OnoYuta/laravel-blog-sample#86]
this Issue used to organize an overview of problems and solutions
### Solution

https://laravel-admin.org/docs/zh/frontend

#### Laravel-admin用のscssファイルを作成

resources/sass/backend/laravel-admin.scss

``` scss
// Fonts
@import url('https://fonts.googleapis.com/css2?family=Quicksand&display=swap');

// Variables
@import 'components/variables';

// Components
@import 'components/laravel-admin';
```

resources/sass/backend/components/_laravel-admin.scss
※Laravel-adminデフォルトのcssが先に読み込まれるようなので、!importantをつけて対応（他に方法があれば修正したい）

```scss
/* Body */

body {
  font-family: $font-family-base !important;
}

/* Header */

.skin-blue-light .main-header .logo {
  background-color: $gray-800 !important;
}

.skin-blue-light .main-header .navbar {
  background-color: $gray-800 !important;
}

.skin-blue-light .main-header .navbar .sidebar-toggle:hover {
  background-color: $gray-800 !important;
}

/* Side Bar */

.skin-blue-light .sidebar a {
  color: $gray-100 !important;
}

.skin-blue-light .sidebar-menu>li.header {
    color: $gray-100 !important;
    background-color: $gray-800 !important;
}

.skin-blue-light .wrapper, .skin-blue-light .main-sidebar, .skin-blue-light .left-side {
  background-color: $gray-800 !important;
}

.skin-blue-light .sidebar-menu>li:hover>a, .skin-blue-light .sidebar-menu>li.active>a {
  background-color: $gray-800 !important;
}

.skin-blue-light .sidebar-menu>li>.treeview-menu {
  background-color: $gray-800 !important;
}

.skin-blue-light.sidebar-mini.sidebar-collapse .sidebar-menu>li>.treeview-menu {
  border-left: 1px solid $gray-800 !important;
}

/* Main */

.content-wrapper, .right-side {
  background-color: $gray-100 !important;
}

a {
  color: $blue;
}

span.bg-light-blue, span.label-primary, span.modal-primary .modal-body {
  background-color: $keppei !important;
}

span.bg-green, span.calloutspan.callout-success, span.alert-success, span.label-success, span.modal-success span.modal-body {
  background-color: $green !important;
}

/* Grid */
.btn-dropbox {
  background-color: $blue !important;
}

.btn-instagram {
  background-color: $ming !important;
}

.btn-twitter{
  background-color: $blue !important;
}

.btn-primary {
  background-color: $blue !important;
  border-color: $blue !important;
}

.btn-success {
  background-color: $green !important;
  border-color: $green !important;
}

.btn-warning {
  background-color: $yellow !important;
  border-color: $yellow !important;
}

.pagination>.active>a, .pagination>.active>a:focus, .pagination>.active>a:hover, .pagination>.active>span, .pagination>.active>span:focus, .pagination>.active>span:hover {
  background-color: $blue !important;
  border-color: $blue !important;
}

/* Footer */

.main-footer {
  background-color: $gray-800 !important;
  color: darken($gray-100, 30%) !important;
}

.main-footer a {
  color: $gray-100 !important;
}

.skin-blue-light .content-wrapper, .skin-blue-light .main-footer {
  border-left: 1px solid lighten($gray-800, 10%) !important;
}
```

#### webpack.mix.jsを修正

webpack.mix.js

```js
mix
   .sass('resources/sass/backend/app.scss', 'public/backend/css')
   .sass('resources/sass/backend/laravel-admin.scss', 'public/backend/css') // 追記
   .sass('resources/sass/frontend/app.scss', 'public/frontend/css')
   .sass('resources/sass/frontend/welcome.scss', 'public/frontend/css')
   .js('resources/js/app.js', 'public/js');
```

#### 自作したcssを読み込む

app/Admin/bootstrap.php

```php
Encore\Admin\Form::forget(['map', 'editor']);
Admin::css('backend/css/laravel-admin.css'); // 追記
```

### Testing

修正前

![スクリーンショット 2020-05-31 12 26 54](https://user-images.githubusercontent.com/49770211/83343797-0aa15f80-a33a-11ea-93bb-8ce55b25f30a.png)

修正後

![スクリーンショット 2020-05-31 17 59 44](https://user-images.githubusercontent.com/49770211/83348616-4dc6f700-a369-11ea-9cab-cd3c1dc1e3b5.png)
